### ISSUE TITLE
How to use BPT Estimation code? 

### ISSUE THREAD

**Issue by Nimesh-Patel** [sparkfun/SparkFun_Pulse_Oximeter_Heart_Rate_Sensor#2]
## Subject: How to use BPT Estimation code? 
Hi,
I am trying to use SparkFun Pulse Oximeter and Heart Rate Sensor - MAX30101 & MAX32664 (Qwiic) and measure BPT Estimation. 
The SparkFun_Bio_Sensor_Hub_Library.cpp file (line 1172 and onwards) suggests the function to measure BPT. 
// ------------------Function Below for MAX32664 Version D (Blood Pressure) ----

The example code shows the heartrate measurement: How do I request to measure the BPT estimates and display Systolic and Diastolic values?

void loop(){

    // Information from the readBpm function will be saved to our "body"
    // variable.  
    body = bioHub.readBpm();
    Serial.print("Heartrate: ");
....................

**Comment by edspark** [comment]
Unfortunately this product does not use the sensor that is capable of providing systolic or diastolic values; this uses MAX32664**A**, and you would want MAX32664**D**. Hope that's helpful.

**Comment by Nimesh-Patel** [comment]
Thank you edspark,
Please is there any place I can purchase MAX32664D sensor and GitHub repo with example code? I appreciate your quick response. 
Thank You,
Nimesh
