### ISSUE TITLE
To Measure BPT usingMAX32664D sensor GitHub repo with example code

### ISSUE THREAD

**Issue by Nimesh-Patel** [sparkfun/SparkFun_Pulse_Oximeter_Heart_Rate_Sensor#3]
Please is there any place I can purchase MAX32664D sensor and GitHub repo with example code to measure BPT?

Thank You,
Nimesh

**Comment by edspark** [comment]
Here is the manufacturer of the part, they're likely to have development boards based around their sensors: 
https://www.analog.com/en/index.html
